name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        sudo apt-get install libncursesw5-dev
        ./autogen.sh
        ./configure
        make

#  build-macos-latest:
#    runs-on: macos-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: make
#      run: |
#        ./autogen.sh
#        ./configure
#        make
